### ISSUE TITLE
File got replace but got an exception.

### ISSUE THREAD

**Issue by akhilg-9** [SNNafi/media_store_plus#26] opened 2024-11-03 05:20 UTC
D/DirName (29532): Download
D/DisplayName Teddy.zip(29532): null
D/saveFile<isReplaced>(29532): false
D/CompatibilityChangeReporter(29532): Compat change id reported: 150939131; UID 10587; state: ENABLED
E/saveFile(29532): UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
E/saveFile(29532): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
E/saveFile(29532): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:178)
E/saveFile(29532): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
E/saveFile(29532): 	at android.content.ContentProviderProxy.update(ContentProviderNative.java:685)
E/saveFile(29532): 	at android.content.ContentResolver.update(ContentResolver.java:2429)
E/saveFile(29532): 	at android.content.ContentResolver.update(ContentResolver.java:2391)
E/saveFile(29532): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.createOrUpdateFile(MediaStorePlusPlugin.kt:305)
E/saveFile(29532): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.saveFile(MediaStorePlusPlugin.kt:183)
E/saveFile(29532): 	at com.snnafi.media_store_plus.MediaStorePlusPlugin.onMethodCall(MediaStorePlusPlugin.kt:66)
E/saveFile(29532): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/saveFile(29532): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/saveFile(29532): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/saveFile(29532): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/saveFile(29532): 	at android.os.Handler.handleCallback(Handler.java:958)
E/saveFile(29532): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/saveFile(29532): 	at android.os.Looper.loopOnce(Looper.java:230)
E/saveFile(29532): 	at android.os.Looper.loop(Looper.java:319)
E/saveFile(29532): 	at android.app.ActivityThread.main(ActivityThread.java:9063)
E/saveFile(29532): 	at java.lang.reflect.Method.invoke(Native Method)
E/saveFile(29532): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
E/saveFile(29532): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

  Future<void> downloadAndSaveFile(String fileUrl, String fileName) async {
    try {
      // Create a temporary directory
      Directory? tempDir = await getDownloadsDirectory();
      String tempFilePath = '${tempDir?.path}/$fileName';

      // Download the file to the temporary directory
      Dio dio = Dio();
      await dio.download(fileUrl, tempFilePath);

      // Save the file to the Downloads directory
      await MediaStore().saveFile(
        tempFilePath: tempFilePath,
        dirType: DirType.download,
        relativePath: AppConstants.appName,
        dirName: DirName.download,
      );

      // Clean up the temporary file
      await File(tempFilePath).delete();

      print('File downloaded and saved successfully.');
    } catch (e) {
      print('Error downloading and saving file: $e');
    }
  }

**Comment by SNNafi** [comment] 2024-11-03 09:22
```shell

D/CompatibilityChangeReporter(29532): Compat change id reported: 150939131; UID 10587; state: ENABLED
E/saveFile(29532): UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
E/saveFile(29532): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: files._data (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])

```

This issue is not related to the plugin. It looks like in the `ContentResolver`.

However, can you provide me with a reproducible code to check?

**Comment by SNNafi** [comment] 2024-11-07 10:27
Closing this, as there is no update.

**Closed as completed by SNNafi** 2024-11-07 10:27 UTC
Labels: question
