### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by SannyRai** [SNNafi/media_store_plus#14] opened 2024-01-19 07:19 UTC
When trying to save image file, encountered NullPointerException in device of sdk 29.

However when dirType is other than photo, its working as expected.

![Screenshot 2024-01-19 at 1 03 38 PM](https://github.com/SNNafi/media_store_plus/assets/112604826/d282c3ec-db8c-4088-a6b5-0d61d01b33d5)

**Comment by SNNafi** [comment] 2024-04-12 02:59
@SannyRai, please check the latest version i.e. `0.0.9`

It should be fixed. However, I couldn't reproduce this. But try the latest version. There are some changes made for API level 29.

**Closed as completed by SNNafi** 2024-04-12 02:59 UTC
